### PR TITLE
Senior exec

### LINKED ISSUE #29: Create mentors section. New mockups are on the way - perhaps lets not work on this right now

### PR DESCRIPTION
**Pull request by malakali542**
- basically complete, just to look at small screen hover text positioning

close #29

### CODE REVIEW

File: src/Components/LandingPage/Landing.js [hunk 1]
```diff
@@ -10,11 +10,14 @@ import MainImage from "./MainImage.js";
 import AboutMax from "./AboutMax.js";
 import Features from "./Features.js";
 import ScrollToTop from "./ScrollToTop.js";
-import Footer from "./Footer.js";
+//import Footer from "./Footer.js";
```
Comment (ahmedhamodi) [inline src/Components/LandingPage/Landing.js:13]: Can you put this back? 😛

File: src/Components/LandingPage/Landing.js [hunk 2]
```diff
@@ -10,11 +10,14 @@ import MainImage from "./MainImage.js";
...
 import Membership from "./Membership.js";
 import SignIn from "../Authentication/SignIn";
 import Carousal from "./Carousal.js";
 import Registration from "../Registration/Registration";
+import SeniorExec from './SeniorExec';
```
Comment (ahmedhamodi) [inline src/Components/LandingPage/Landing.js:18]: I don't think you need this import, just `SeniorExecGrid` is needed on Landing.js

File: src/Components/LandingPage/Landing.js [hunk 3]
```diff
@@ -171,10 +174,11 @@ class Landing extends Component{
                         <Features/>
                         <JobSection/>
                         <Membership/>
+                        <SeniorExecGrid/>
                         <Carousal/>
 
                         {/* Scroll to top and footer components at bottom */}
-                        <Footer/>
+                        {/* <Footer/> */}
```
Comment (ahmedhamodi) [inline src/Components/LandingPage/Landing.js:181]: Add back

File: src/Components/LandingPage/SmallSeniorExec.js [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+             <div className={classes.sectionstyle}>
+                           
+                 
+
+                <h3 className={classes.hovertext} style={{display: this.state.text}} onMouseEnter={this.handleEnter} 
+                 onMouseLeave={this.handleExit}>{this.props.name_text}</h3>
+                <h3 className={classes.extratext} style={{display: this.state.text}} onMouseEnter={this.handleEnter} 
+                 onMouseLeave={this.handleExit}>{this.props.extra_text}</h3>
+                
+                <img style={{width: '100%', marginTop: '0vh', marginBottom:'4vh', display: this.state.display1, borderTopLeftRadius: '30%', borderBottomRightRadius: '30%'}}
```
Comment (ahmedhamodi) [inline src/Components/LandingPage/SmallSeniorExec.js:111]: Can you move these styles to the makeStyles above? Also, in the wireframes the bottom border radius is larger than the top one. Can you try with 50% bottom radius and see if it looks like the wireframe?

Comment (ahmedhamodi) [reply src/Components/LandingPage/SmallSeniorExec.js:111]: Same for all the other files, inline styling should only really be used for 1/2 attributes. Also if the styling is used in multiple places, I really would like it above so it's easier to change.

File: src/Components/LandingPage/SeniorExecGrid.js [hunk 5]
```diff
@@ -0,0 +1,202 @@
...
+                name_text="Latafat Faran"
+                extra_text="Executive Vice President at Core Development Group"
+                image = {SmallSeniorExecImg}
+                hover_image = {SmallSeniorExecImgHover}
+              />
+            </Grid>
+          </Grid>
+        </div>
+
+          <div className={classes.background} style={{display: window.innerWidth > 800 ? 'None' : ''}}>
```
Comment (ahmedhamodi) [inline src/Components/LandingPage/SeniorExecGrid.js:152]: Have you tried getting this working with the Boxes and the xs/sm/md tags to be responsive? Also, if we want to keep this, I think 900 is probably a better value to use.

Also, on the smaller screens, the two smaller exec images have no spacing between them:
image

And as you mentioned, the text on this screen doesn't fit. Look into setting the inner text as `1.5vw` or another dynamic variable. Fatum did this with the Jobs section.

File: src/Components/LandingPage/Landing.js (hunk 3 above)
Comment (ahmedhamodi) [reply src/Components/LandingPage/Landing.js:181]: Also put the senior exec grid below features component and above jobs, it's in the wrong place right now

File: src/Components/LandingPage/SeniorExecGrid.js [hunk 6]
```diff
@@ -0,0 +1,202 @@
...
+import SmallSeniorExecBottom from "./SeniorExecSmallBottom";
+import SeniorExecImg from "../Images/senior/Salman_Zahid (1).jpg"
+import SeniorExecImgHover from "../Images/senior/Salman_Zahid2.jpg"
+
+const useStyles = makeStyles(() => ({
+  background: { 
+    backgroundColor: 'white',
+  },
+  seniorexec:{
+    marginTop :'10vh',
```
Comment (ahmedhamodi) [inline src/Components/LandingPage/SeniorExecGrid.js:18]: use 1paddingTop: '10vh'` so the background color is preserved.

File: src/Components/LandingPage/SmallSeniorExec.js (hunk 4 above)
Comment (ahmedhamodi) [reply src/Components/LandingPage/SmallSeniorExec.js:95]: Need to investigate how this works with state variables deciding the css. For now I will leave as is.
